language: go

go:
  - release

before_install:
  # Setup dependency management tool
  - curl -L -s https://github.com/golang/dep/releases/download/v0.3.1/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure

script:
  - go test -cover -race -v $(go list ./... | grep -v /vendor/ | grep -v /integration | tr "\n" " ") -coverprofile=coverage.txt -covermode=atomic
  - go build -o bin/account cmd/account/account_server.go

after_success:
  - bash <(curl -s https://codecov.io/bash)
